### ISSUE TITLE
Class 'XMLWriter' not found

### ISSUE THREAD

**Issue by BooVeMan** [upshift-docker/dolibarr#7]
Hi, I enabled the import/export module in dolibarr and try to download a sample data set for Excel2007 to import product data  (URL is `http://localhost:8080/imports/import.php?step=2&datatoimport=produit_1&format=xlsx&excludefirstline=1&separator=%2C&enclosure=%22`) as a result the error will issue an 500-error with the following log message:
```
[Mon Mar 16 16:56:06.311385 2020] [php7:error] [pid 36] [client 172.17.0.1:48550] PHP Fatal error:  Uncaught Error: Class 'XMLWriter' not found in /var/www/html/includes/phpoffice/phpexcel/Classes/PHPExcel/Shared/XMLWriter.php:44\nStack trace:\n#0 /var/www/html/includes/phpoffice/phpexcel/Classes/PHPExcel/Autoloader.php(86): require()\n#1 [internal function]: PHPExcel_Autoloader::Load('PHPExcel_Shared...')\n#2 /var/www/html/includes/phpoffice/phpexcel/Classes/PHPExcel/Writer/Excel2007/ContentTypes.php(53): spl_autoload_call('PHPExcel_Shared...')\n#3 /var/www/html/includes/phpoffice/phpexcel/Classes/PHPExcel/Writer/Excel2007.php(246): PHPExcel_Writer_Excel2007_ContentTypes->writeContentTypes(Object(PHPExcel), false)\n#4 /var/www/html/core/modules/import/import_xlsx.modules.php(221): PHPExcel_Writer_Excel2007->save('/tmp/dolAKCBfn')\n#5 /var/www/html/imports/class/import.class.php(228): ImportXlsx->write_footer_example(Object(Translate))\n#6 /var/www/html/imports/emptyexample.php(105): Import->build_example_file('xlsx', Array, Array, 'produit_1')\n#7 {main}\n  thrown in /var/www/html/includes/phpoffice/phpexcel/Classes/PHPExcel/Shared/XMLWriter.php on line 44, referer: http://localhost:8080/imports/import.php?step=2&datatoimport=produit_1&format=xlsx&excludefirstline=1&separator=%2C&enclosure=%22
[Mon Mar 16 16:56:06.671936 2020] [php7:error] [pid 37] [client 172.17.0.1:48552] PHP Fatal error:  Uncaught Error: Class 'XMLWriter' not found in /var/www/html/includes/phpoffice/phpexcel/Classes/PHPExcel/Shared/XMLWriter.php:44\nStack trace:\n#0 /var/www/html/includes/phpoffice/phpexcel/Classes/PHPExcel/Autoloader.php(86): require()\n#1 [internal function]: PHPExcel_Autoloader::Load('PHPExcel_Shared...')\n#2 /var/www/html/includes/phpoffice/phpexcel/Classes/PHPExcel/Writer/Excel2007/ContentTypes.php(53): spl_autoload_call('PHPExcel_Shared...')\n#3 /var/www/html/includes/phpoffice/phpexcel/Classes/PHPExcel/Writer/Excel2007.php(246): PHPExcel_Writer_Excel2007_ContentTypes->writeContentTypes(Object(PHPExcel), false)\n#4 /var/www/html/core/modules/import/import_xlsx.modules.php(221): PHPExcel_Writer_Excel2007->save('/tmp/dolmfPBEN')\n#5 /var/www/html/imports/class/import.class.php(228): ImportXlsx->write_footer_example(Object(Translate))\n#6 /var/www/html/imports/emptyexample.php(105): Import->build_example_file('xlsx', Array, Array, 'produit_1')\n#7 {main}\n  thrown in /var/www/html/includes/phpoffice/phpexcel/Classes/PHPExcel/Shared/XMLWriter.php on line 44
```
I already tried adding `php7-xml` by `apk add php7-xml` and restarting the container, but no change in the error message

**Comment by laurpaum** [comment]
Fixed by c16f23d075bc563fbdf009b92a5de569383cd507, XMLReader and XMLWriter required additional libraries provided by php7-xmlreader and php7-xmlwriter apk packages
